spring:
  application:
    name: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/master/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:2209/spring_s1
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

app:
  oauth2:
    client-id: spring-s1
